version: "3"

tasks:
  default:
    cmds:
    - task --list-all
    desc: "List all available tasks in this Taskfile."

  create-cluster:
    cmds:
    - kind create cluster --name sql-server-testing-cluster
    desc: "Create a Kind Kubernetes cluster named 'sql-server-testing-cluster' for testing purposes."

  delete-cluster:
    cmds:
    - kind delete cluster --name sql-server-testing-cluster
    desc: "Delete the Kind Kubernetes cluster named 'sql-server-testing-cluster'."

  create-crd-files:
    internal: true
    dir: ./src/OperatorTemplate.Operator
    cmds:
    - powershell -Command "if (Test-Path ./config) { Get-ChildItem -Path ./config -Recurse -Force | Remove-Item -Recurse -Force; Remove-Item -Force ./config }"
    - dotnet clean
    - dotnet build
    - powershell -Command "remove-item -recurse -force ./Dockerfile"
    desc: "Internal task: Generate a fresh configuration for the OperatorTemplate.Operator by cleaning and rebuilding the project."

  copy-to-helm:
    internal: true
    dir: .
    cmds:
    - powershell -Command "Copy-Item -Path './src/OperatorTemplate.Operator/config/crds/*' -Destination './operator-chart/crds/' -Recurse -Force -Exclude 'kustomization.yaml'"

    desc: "Internal task: Copy configuration and CRD files to the Helm chart directories."

  create-crds-and-copy:
    cmds:
    - task: create-crd-files
    - task: copy-to-helm
    desc: "Create the Custom Resource Definitions (CRDs) for the OperatorTemplate.Operator and copy them to the Helm chart directories."

  install-helm-chart:
    dir: ./operator-chart
    cmds:
    - helm upgrade --install sql-server . --namespace sql-server --create-namespace --wait
    desc: "Deploy the Helm chart for the OperatorTemplate stack."

  uninstall-helm-chart:
    dir: ./operator-chart
    cmds:
    - helm uninstall sql-server --namespace sql-server
    desc: "Uninstall the Helm chart for the OperatorTemplate stack."

  apply-crds-from-helm-chart:
    dir: ./operator-chart
    cmds:
    - kubectl apply -f ./crds
    desc: "Apply the Custom Resource Definitions (CRDs) from the Helm chart to the Kubernetes cluster."
    internal: true

  delete-crd-from-cluster:
    dir: ./operator-chart
    cmds:
    - kubectl delete -f ./crds
    desc: "Delete the Custom Resource Definition (CRD) for the OperatorTemplate.Operator from the Kubernetes cluster."

  dev:
    dir: ./src/OperatorTemplate.AppHost
    cmds:
    - dotnet watch
    desc: "Start the development environment for the OperatorTemplate.AppHost with live file watching enabled."

  apply-crd-instance:
    cmds:
    - kubectl apply -f ./local-configs
    desc: "Apply the Custom Resource Instance (CRI) for the OperatorTemplate.Operator."

  delete-crd-instance:
    cmds:
    - kubectl delete -f ./local-configs/sql-server-instance.yaml
    desc: "Delete the Custom Resource Instance (CRI) for the OperatorTemplate.Operator."

  build-container-image:
    dir: ./src/OperatorTemplate.Operator
    cmds:
    - docker compose build
    desc: "Build the Docker image for the OperatorTemplate.Operator."

  load-image-into-kind:
    cmds:
    - kind load docker-image operator-template:latest --name sql-server-testing-cluster
    desc: "Load the OperatorTemplate.Operator Docker image into the Kind Kubernetes cluster."

  quick-deploy:
    cmds:
    - task delete-cluster
    - task create-cluster
    - task create-crds-and-copy
    - task build-container-image
    - task load-image-into-kind
    - task install-helm-chart
    - task apply-crd-instance
    desc: "Start the full OperatorTemplate stack in the Kind Kubernetes cluster."

  quick-dev:
    cmds:
    - task delete-cluster
    - task create-cluster
    - task create-crds-and-copy
    - task: apply-crds-from-helm-chart
    - task apply-crd-instance
    - task dev
