version: "3"

includes:

  cluster:
    taskfile: ./local-configs/Taskfile.yaml
    dir: ./local-configs
    internal: false

  operator-chart:
    taskfile: ./operator-chart/Taskfile.yaml
    dir: ./operator-chart
    internal: false

  mssql-tools:
    taskfile: ./container-images/mssql-tools/Taskfile.yaml
    dir: ./container-images/mssql-tools
    internal: true

tasks:
  default:
    cmds:
    - go-task --list-all
    desc: "List all available tasks in this Taskfile."

  create-crd-files:
    internal: true
    dir: ./src/OperatorTemplate.Operator
    cmds:
    - pwsh -Command "if (Test-Path ./config) { Get-ChildItem -Path ./config -Recurse -Force | Remove-Item -Recurse -Force; Remove-Item -Force ./config }"
    - dotnet clean
    - dotnet build
    - pwsh -Command "remove-item -recurse -force ./Dockerfile"
    desc: "Internal task: Generate a fresh configuration for the OperatorTemplate.Operator by cleaning and rebuilding the project."

  copy-to-helm:
    internal: true
    dir: .
    cmds:
    - pwsh -Command "Copy-Item -Path './src/OperatorTemplate.Operator/config/crds/*' -Destination './operator-chart/crds/' -Recurse -Force -Exclude 'kustomization.yaml'"

    desc: "Internal task: Copy configuration and CRD files to the Helm chart directories."

  create-crds-and-copy:
    cmds:
    - task: create-crd-files
    - task: copy-to-helm
    desc: "Create the Custom Resource Definitions (CRDs) for the OperatorTemplate.Operator and copy them to the Helm chart directories."

  build-operator-image:
    cmds:
    - docker build -t operator-template:latest -f ./src/OperatorTemplate.Operator/Containerfile .
    - docker tag operator-template:latest localhost:5001/operator-template:latest
    - docker push localhost:5001/operator-template:latest

    desc: "Build the Docker image for the OperatorTemplate.Operator."

  dev:
    dir: ./src/OperatorTemplate.AppHost
    cmds:
    - dotnet watch
    desc: "Start the development environment for the OperatorTemplate.AppHost with live file watching enabled."

  quick-deploy:
    cmds:
    - task: cluster:create-registry
    - task: cluster:delete
    - task: cluster:create
    - task: create-crds-and-copy
    - task: mssql-tools:build
    - task: mssql-tools:load-image-into-kind
    - task: build-operator-image
    - go-task cluster:loadimage -- localhost:5001/operator-template:latest
    - go-task cluster:loadimage -- mcr.microsoft.com/mssql/server:2022-latest
    - task: operator-chart:install-helm-chart
    - task: cluster:apply-crd-instance
    desc: "Start the full OperatorTemplate stack in the Kind Kubernetes cluster."

  quick-dev:
    cmds:
    - task: cluster:delete
    - task: cluster:create
    - go-task cluster:loadimage -- mcr.microsoft.com/mssql/server:2022-latest
    - task: mssql-tools:build
    - task: mssql-tools:load-image-into-kind
    - task: create-crds-and-copy
    - task: operator-chart:apply-crds-from-helm-chart
    - task: cluster:apply-crd-instance
    - task: dev
