# SQL Server Command Line Tools
FROM almalinux:9.5

# adding custom MS repository
RUN dnf install -y https://packages.microsoft.com/config/rhel/9.0/packages-microsoft-prod.rpm

# install SQL Server drivers and tools
RUN ACCEPT_EULA=Y dnf install -y msodbcsql18 mssql-tools18

# add the binary location to the $PATH
RUN echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
RUN /bin/bash -c "source ~/.bashrc"

CMD /bin/bash