---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-operator-rb
  labels:
    app: operator
    release: "{{ .Release.Name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-operator-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-operator-sa
    namespace: {{ .Release.Namespace }}
