---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-operator-role
rules:
# Custom Resource Definitions - full access to our CRDs
- apiGroups:
  - sql-server.dotkube.io
  resources:
  - sqlservers
  - externalsqlservers
  - databases
  - sqlserverlogins
  - sqlserverusers
  - sqlserverschemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Custom Resource Status subresources
- apiGroups:
  - sql-server.dotkube.io
  resources:
  - sqlservers/status
  - externalsqlservers/status
  - databases/status
  - sqlserverlogins/status
  - sqlserverusers/status
  - sqlserverschemas/status
  verbs:
  - get
  - patch
  - update

# Secrets - needed to read SA passwords and manage secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch

# ConfigMaps - needed to create SQL Server configuration
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch

# Services - needed to create SQL Server services
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch

# Events - needed to emit Kubernetes events
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update

# StatefulSets - needed to create SQL Server statefulsets
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - get
  - list
  - watch

# Leases - needed for leader election
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
  - watch

# CustomResourceDefinitions - needed for CRD installer to check/install CRDs
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - watch
