
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-selfsigned-cert
  namespace: {{ .Values.gateway.ns }}
spec:
  secretName: {{ .Values.gateway.tlsSecretName }}
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: "*.localhost"
  dnsNames:
    - "*.localhost"