
---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.gateway.host | quote }}
      tls:
        httpsRedirect: {{ .Values.gateway.forceHttpToHttps }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - {{ .Values.gateway.host | quote }}
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.gateway.tlsSecretName }}
    - port:
        number: 1433
        name: tcp-sql
        protocol: TCP
      hosts:
        - {{ .Values.gateway.host | quote }}