
---

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: kiali
spec:
  hosts:
    - kiali.localhost
  gateways:
    - "{{ .Values.gateway.name }}"
  http:
    - route:
        - destination:
            host: kiali.istio-system.svc.cluster.local
            port:
              number: 20001

---

apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: kiali
spec:
  host: kiali.istio-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE