---

apiVersion: v1
kind: Namespace
metadata:
  name: sqlserver-example


---


apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
  namespace: sqlserver-example
type: Opaque
stringData:
  sa-password: SuperSecretPassword123!

---



apiVersion: sql-server.dotkube.io/v1alpha1
kind: SQLServer
metadata:
  name: sqlserver-instance
  namespace: sqlserver-example
spec:
  version: "2022"
  storageClass: "standard"
  storageSize: "6Gi"
  secretName: "sqlserver-secret"
  serviceType: "LoadBalancer"
  enableFullTextSearch: true


---


apiVersion: sql-server.dotkube.io/v1alpha1
kind: Database
metadata:
  name: example-database1
  namespace: sqlserver-example
spec:
  instanceName: sqlserver-instance
  databaseName: HelloWorld1




---


apiVersion: sql-server.dotkube.io/v1alpha1
kind: Database
metadata:
  name: example-database2
  namespace: sqlserver-example
spec:
  instanceName: sqlserver-instance
  databaseName: HelloWorld2

