---

apiVersion: v1
kind: Namespace
metadata:
  name: sqlserver-example
  labels:
    istio-injection: enabled


---

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: sqlserver-virtualservice
  namespace: sqlserver-example
spec:
  gateways:
    - istio-gateways/localhost-gateway
  hosts:
    - "first-sql.localhost"
    - "first-sql.local-cluster.com"
  tcp:
    - match:
        - port: 1433
      route:
        - destination:
            host: sqlserver-instance-headless
            port:
              number: 1433

---

apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
  namespace: sqlserver-example
type: Opaque
stringData:
  sa-password: "RunningMan323#"

---



apiVersion: database.example.com/v1alpha1
kind: SQLServer
metadata:
  name: sqlserver-instance
  namespace: sqlserver-example
spec:
  version: "2022"
  storageClass: "standard"
  storageSize: "6Gi"
  secretName: "sqlserver-secret"


---


apiVersion: database.example.com/v1alpha1
kind: Database
metadata:
  name: example-database
  namespace: sqlserver-example
spec:
  instanceName: sqlserver-instance
  databaseName: hello-world