
auth:
  strategy: "anonymous"





server:
  web_fqdn: "kiali.localhost"
  web_port: 443
  web_scheme: "https"
  web_root: "/"


external_services:
  prometheus:
    url: http://kube-prometheus-stack-prometheus.monitoring.svc:9090