apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - sql-server.dotkube.io
  - coordination.k8s.io
  resources:
  - databases
  - sqlserverusers
  - sqlservers
  - sqlserverlogins
  - leases
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
- apiGroups:
  - sql-server.dotkube.io
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sql-server.dotkube.io
  resources:
  - sqlserverusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sql-server.dotkube.io
  resources:
  - sqlservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sql-server.dotkube.io
  resources:
  - sqlserverlogins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update