apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalsqlservers.sql-server.dotkube.io
spec:
  group: sql-server.dotkube.io
  names:
    kind: ExternalSQLServer
    listKind: ExternalSQLServerList
    plural: externalsqlservers
    singular: externalsqlserver
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status of the external SQL Server connection.
            properties:
              state:
                description: The current state of the connection.
                type: string
              message:
                description: A message providing details on the current connection status.
                type: string
              lastChecked:
                description: The last time the connection was verified.
                format: date-time
                nullable: true
                type: string
              isConnected:
                description: Whether the connection to the external SQL Server is healthy.
                type: boolean
            type: object
          spec:
            description: Spec of the external SQL Server connection.
            properties:
              host:
                description: The hostname or IP address of the SQL Server instance (e.g., myserver.database.windows.net, 10.0.0.5, mydatabase.rds.amazonaws.com).
                type: string
              port:
                description: The port number for the SQL Server connection.
                format: int32
                type: integer
              secretName:
                description: The name of the Kubernetes secret containing SQL Server credentials (must contain 'password' keys).
                type: string
              useEncryption:
                description: Whether to use SSL/TLS encryption for the connection.
                type: boolean
              trustServerCertificate:
                description: Whether to trust the server certificate (set to true for self-signed certificates).
                type: boolean
              additionalConnectionProperties:
                additionalProperties:
                  type: string
                description: Optional connection string parameters as key-value pairs (e.g., for Azure AD authentication, connection timeout, etc.).
                nullable: true
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}