apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sqlserverlogins.sql-server.dotkube.io
spec:
  group: sql-server.dotkube.io
  names:
    kind: SQLServerLogin
    listKind: SQLServerLoginList
    plural: sqlserverlogins
    singular: sqlserverlogin
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status of the SQL Server login.
            properties:
              state:
                description: The current state of the SQL Server login.
                type: string
              message:
                description: A message indicating the current status of the SQL Server login.
                type: string
              lastChecked:
                description: The last time the login status was checked.
                format: date-time
                nullable: true
                type: string
            type: object
          spec:
            description: Spec of the SQL Server login.
            properties:
              sqlServerName:
                description: The name of the SQL Server instance.
                type: string
              loginName:
                description: The login name for authentication.
                type: string
              authenticationType:
                description: The authentication type for the login (e.g., SQL, Windows).
                type: string
              secretName:
                description: The name of the Kubernetes secret storing authentication credentials.
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}