apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sqlserverschemas.sql-server.dotkube.io
spec:
  group: sql-server.dotkube.io
  names:
    kind: SQLServerSchema
    listKind: SQLServerSchemaList
    plural: sqlserverschemas
    singular: sqlserverschema
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status of the SQL Server database schema.
            properties:
              state:
                description: The current state of the schema.
                type: string
              message:
                description: A message indicating the current status of the schema.
                type: string
              lastChecked:
                description: The last time the schema status was checked.
                format: date-time
                nullable: true
                type: string
            type: object
          spec:
            description: Spec of the SQL Server database schema.
            properties:
              instanceName:
                description: The SQL Server instance name where the schema will be created.
                type: string
              databaseName:
                description: The name of the database to create the schema in.
                type: string
              schemaName:
                description: The name of the schema to be created.
                type: string
              schemaOwner:
                description: The database user that owns this schema.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}