apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sqlservers.sql-server.dotkube.io
spec:
  group: sql-server.dotkube.io
  names:
    kind: SQLServer
    listKind: SQLServerList
    plural: sqlservers
    singular: sqlserver
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status of the SQL Server deployment.
            properties:
              state:
                description: The current state of the SQL Server deployment.
                type: string
              message:
                description: A message providing details on the current status of SQL Server.
                type: string
            type: object
          spec:
            description: Spec of the SQL Server deployment.
            properties:
              version:
                description: The version of SQL Server to deploy.
                type: string
              storageClass:
                description: The name of the storage class to use for SQL Server storage.
                type: string
              storageSize:
                description: The size of the persistent storage volume.
                type: string
              secretName:
                description: The name of the Kubernetes secret containing SQL Server credentials.
                nullable: true
                type: string
              serviceType:
                description: The type of Kubernetes service to expose SQL Server (e.g., ClusterIP, NodePort, LoadBalancer).
                nullable: true
                type: string
              enableFullTextSearch:
                description: Specifies whether full-text search is enabled in SQL Server.
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}