apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sqlserverusers.sql-server.dotkube.io
spec:
  group: sql-server.dotkube.io
  names:
    kind: SQLServerUser
    listKind: SQLServerUserList
    plural: sqlserverusers
    singular: sqlserveruser
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status of the database user.
            properties:
              state:
                description: The current state of the database user.
                type: string
              message:
                description: A message indicating the current status of the database user.
                type: string
              lastChecked:
                description: The last time the database user status was checked.
                format: date-time
                nullable: true
                type: string
            type: object
          spec:
            description: Spec of the database user.
            properties:
              sqlServerName:
                description: The name of the SQL Server instance.
                type: string
              databaseName:
                description: The name of the database where this user will be created.
                type: string
              loginName:
                description: The login name for the database user.
                type: string
              roles:
                description: The roles assigned to the database user.
                items:
                  type: string
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}