kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"

name: sql-server-testing-cluster

nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 1434
    protocol: TCP
