
services:
  registry:
    image: docker.io/registry:2
    container_name: kind-registry
    restart: always
    ports:
      - "5000:5000"
    networks:
      - kind

networks:
  kind:
    driver: bridge