version: "3"

tasks:

  create:
    cmds:
    - kind delete cluster --name sql-server-testing-cluster
    - kind create cluster --config ./kind-config.yaml
    - docker pull mcr.microsoft.com/mssql/server:2022-latest
    - kind load docker-image mcr.microsoft.com/mssql/server:2022-latest --name sql-server-testing-cluster
    - task: create-registry
    - bash ./scripts/configure-registry-with-kind.sh

    - task: install-helm-repo-updates
    desc: "Create a Kind Kubernetes cluster named 'sql-server-testing-cluster' for testing purposes."

  delete:
    cmds:
    - kind delete cluster --name sql-server-testing-cluster
    desc: "Delete the Kind Kubernetes cluster named 'sql-server-testing-cluster'."

  install-helm-repo-updates:
    cmds:
    - |
      helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      helm repo add metallb https://metallb.github.io/metallb

      helm repo update

    desc: "Installs all of the necessary Helm charts for the OperatorTemplate stack."
    ignore_error: true

  loadimage:
    desc: "Load an image into the Kind Kubernetes cluster. Usage: task load-image <image-name>"
    cmds:
    - kind load docker-image {{.CLI_ARGS}} --name sql-server-testing-cluster

  apply-crd-instance:
    cmds:
    - kubectl apply -f ./example.yaml
    desc: "Apply the Custom Resource Instance (CRI) for the OperatorTemplate.Operator."

  delete-crd-instance:
    cmds:
    - kubectl delete -f ./example.yaml
    desc: "Delete the Custom Resource Instance (CRI) for the OperatorTemplate.Operator."

  
  create-registry:
    cmds:
    - docker compose -f ./registry.yaml up -d

  
  add-metallb:
    cmds:
      - go install sigs.k8s.io/cloud-provider-kind@latest
      - helm upgrade --wait --install metallb metallb/metallb --namespace metallb-system --create-namespace
      - bash ./scripts/metallb-setup.sh




  test-login:
    cmds:
    - bash ./scripts/test-logins.sh

  create-external-sql-container:
    cmds:
    - docker run -d --name external-sql-server -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=YourStrongPassword123!' -p 1435:1433 mcr.microsoft.com/mssql/server:2022-latest
    desc: "Create a SQL Server container on port 1435 for testing external SQL Server connections."

  delete-external-sql-container:
    cmds:
    - docker stop external-sql-server || true
    - docker rm external-sql-server || true
    desc: "Delete the external SQL Server container."

  apply-external-crd-instance:
    cmds:
    - kubectl apply -f ./external-sql-example.yaml
    desc: "Apply the External SQL Server Custom Resource Instance."

  delete-external-crd-instance:
    cmds:
    - kubectl delete -f ./external-sql-example.yaml
    desc: "Delete the External SQL Server Custom Resource Instance."


