---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-operator-role
  labels:
    app: operator
    release: "{{ .Release.Name }}"
rules:
  - apiGroups: ["*"] # Match all API groups
    resources: ["*"] # Match all resource types
    verbs: ["*"]     # Allow all actions (create, update, delete, etc.)
