version: "3"

tasks:
  install-helm-chart:
    cmds:
    - helm upgrade --install sql-server . --namespace sql-server --create-namespace
    desc: "Deploy the Helm chart for the OperatorTemplate stack."

  uninstall-helm-chart:
    cmds:
    - helm uninstall sql-server --namespace sql-server
    desc: "Uninstall the Helm chart for the OperatorTemplate stack."

  apply-crds-from-helm-chart:
    cmds:
    - kubectl apply -f ./crds
    desc: "Apply the Custom Resource Definitions (CRDs) from the Helm chart to the Kubernetes cluster."

  delete-crd-from-cluster:
    cmds:
    - kubectl delete -f ./crds
    desc: "Delete the Custom Resource Definition (CRD) for the OperatorTemplate.Operator from the Kubernetes cluster."

  unit-test:
    cmds:
    - helm unittest .
    desc: "Run Helm chart unit tests using helm-unittest plugin."

  lint:
    cmds:
    - helm lint .
    desc: "Lint the Helm chart for potential issues."

  test-all:
    deps:
    - lint
    - unit-test
    desc: "Run both lint and unit tests for the Helm chart."
