apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sqlserverusers.sql-server.dotkube.io
spec:
  group: sql-server.dotkube.io
  names:
    kind: SQLServerUser
    listKind: SQLServerUserList
    plural: sqlserverusers
    singular: sqlserveruser
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              state:
                type: string
              message:
                type: string
              lastChecked:
                format: date-time
                nullable: true
                type: string
            type: object
          spec:
            properties:
              sqlServerName:
                type: string
              databaseName:
                type: string
              loginName:
                type: string
              roles:
                items:
                  type: string
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}