# Build the operator
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /operator

# Copy the entire solution
COPY . .

# Restore dependencies and build the operator
WORKDIR /operator/src/OperatorTemplate.Operator
RUN dotnet restore
RUN curl -L -o cfssl https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssl_1.5.0_linux_amd64
RUN curl -L -o cfssljson https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssljson_1.5.0_linux_amd64
RUN chmod +x ./cfssl ./cfssljson
RUN mkdir out
RUN cp ./cfssl ./cfssljson out/
RUN dotnet publish -c Release -o out

# The runner for the application
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final

# Create a non-root user and group
RUN addgroup k8s-operator && useradd -G k8s-operator operator-user

WORKDIR /operator
COPY --from=build /operator/src/OperatorTemplate.Operator/out/ ./
RUN chown operator-user:k8s-operator -R .

# Run as non-root user
USER operator-user

ENTRYPOINT [ "dotnet", "OperatorTemplate.Operator.dll" ]