apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.sql-server.dotkube.io
spec:
  group: sql-server.dotkube.io
  names:
    kind: Database
    listKind: DatabaseList
    plural: databases
    singular: database
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              state:
                type: string
              message:
                type: string
              lastChecked:
                format: date-time
                nullable: true
                type: string
            type: object
          spec:
            properties:
              instanceName:
                type: string
              databaseName:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}