name: Helm Chart Unit Tests

on:
  pull_request:
    paths:
      - 'deploy/chart/kubesqlserver-operator/**'
      - '.github/workflows/helm-unit-tests.yml'
    branches:
      - main
      - master

jobs:
  helm-unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run Helm tests
        run: |
          docker run --rm --user $(id -u):$(id -g) -v $(pwd):/apps helmunittest/helm-unittest deploy/chart/kubesqlserver-operator
